const fs = require('fs');
const path = require('path');

const POSTS_DIR = path.resolve(__dirname, '..', 'posts');

const TOPICS = [
  'Agentic AI',
  'Multi-agent systems in production',
  'AI-powered workflow automation',
  'Playwright for browser automation',
  'LLM orchestration patterns',
  'Building autonomous AI agents',
  'AI in DevOps pipelines',
  'Retrieval-Augmented Generation (RAG)',
  'Fine-tuning vs prompt engineering',
  'AI safety and alignment',
  'Edge AI and on-device inference',
  'The future of human-in-the-loop AI',
];

function pickTopic() {
  return TOPICS[Math.floor(Math.random() * TOPICS.length)];
}

/**
 * Mock AI generator — placeholder for future Qwen/OpenCode integration.
 * Accepts a topic string, returns a generated LinkedIn post.
 */
async function generateWithAI(topic) {
  // TODO: Replace with actual AI API call (OpenRouter/Qwen)
  const isShortTopic = topic.split(/\s+/).length <= 4;

  const postBody = isShortTopic
    ? [
        `${topic} is reshaping how we work and live. From smart assistants managing our schedules to autonomous agents handling complex workflows, these systems augment human capabilities — offloading repetitive tasks, driving data-backed decisions, and freeing up creativity. In the workplace, teams deploy AI agents to draft reports, triage inquiries, manage timelines, and write code, letting professionals focus on strategic thinking rather than routine chores.`,

        `On a personal level, agentic AI makes daily life easier — personalized learning adapts to students, health assistants monitor vitals, and financial agents optimize budgets. The result is faster turnaround, lower costs, and more time for what truly matters. Agentic AI isn't about replacing humans — it's about empowering them.`,
      ]
    : [
        `Agentic AI is reshaping how developers build, ship, and maintain software — automating code reviews, managing CI/CD, triaging issues, and generating boilerplate. It eases the everyday cognitive load by handling routine tasks, letting engineers focus on architecture, design, and solving meaningful problems. The result is not just faster delivery, but a more professional and intentional approach to development.`,

        `The shift is subtle but profound. Instead of juggling a dozen tools, developers orchestrate intelligent agents that handle the overhead. This doesn't replace engineering judgment — it amplifies it. Fewer context switches, less burnout, more time for creativity and impact. That's the real promise of agentic AI in a developer's daily life.`,
      ];

  const attribution = `— This post was generated by an autonomous AI agent as part of the Agent building project.`;

  return `${postBody.join('\n\n')}\n\n${attribution}`;
}

async function generatePost(topic) {
  if (!topic || typeof topic !== 'string') {
    topic = pickTopic();
    console.log(`No topic given. AI picked: "${topic}"`);
  }

  console.log(`Generating LinkedIn post on: "${topic}"...`);
  const content = await generateWithAI(topic);
  console.log('Post generated successfully.');

  fs.mkdirSync(POSTS_DIR, { recursive: true });

  const filePath = path.join(POSTS_DIR, 'latest-post.txt');
  fs.writeFileSync(filePath, content.trim() + '\n', 'utf-8');

  console.log(`Saved to ${filePath}`);
  return filePath;
}

// CLI entry point
if (require.main === module) {
  const topic = process.argv[2];
  if (!topic) {
    console.error('Usage: node scripts/generate-post.js "<topic>"');
    process.exit(1);
  }
  generatePost(topic).catch((err) => {
    console.error('Error:', err.message);
    process.exit(1);
  });
}

module.exports = { generatePost, generateWithAI };
